// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "MiniMaya.h"

TreeView::TreeView() {
  Fl_Window* w;
  { Fl_Window* o = new Fl_Window(753, 503);
    w = o;
    o->color((Fl_Color)14);
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(500, 351, 130, 44, "Select Vertex");
      { new Fl_Button(525, 355, 40, 30, "<-");
      } // Fl_Button* o
      { new Fl_Button(565, 355, 40, 30, "->");
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(510, 472, 260, 28, "Snowcap Height");
      { Fl_Slider* o = new Fl_Slider(520, 476, 230, 24);
        o->type(1);
      } // Fl_Slider* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(545, 151, 190, 79, "Mesh Color");
      { Fl_Slider* o = new Fl_Slider(546, 153, 189, 20);
        o->type(1);
        o->color(FL_RED);
      } // Fl_Slider* o
      { Fl_Slider* o = new Fl_Slider(546, 173, 189, 20);
        o->type(1);
        o->color((Fl_Color)102);
      } // Fl_Slider* o
      { Fl_Slider* o = new Fl_Slider(546, 193, 189, 21);
        o->type(1);
        o->color((Fl_Color)4);
      } // Fl_Slider* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(10, 9, 500, 500);
      o->labeltype(FL_NO_LABEL);
      { Fl_Box* o = new Fl_Box(10, 9, 500, 500, "tView");
        o->box(FL_FLAT_BOX);
      } // Fl_Box* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(530, 10, 195, 105);
      { new Fl_Input(575, 16, 35, 28, "Rows");
      } // Fl_Input* o
      { new Fl_Input(575, 44, 35, 28, "Cols");
      } // Fl_Input* o
      { new Fl_Button(585, 84, 100, 30, "Create Mesh");
      } // Fl_Button* o
      { new Fl_Input(687, 15, 35, 28, "Unit Width");
      } // Fl_Input* o
      { new Fl_Input(687, 43, 35, 28, "Unit Height");
      } // Fl_Input* o
      o->end();
    } // Fl_Group* o
    { new Fl_Button(620, 255, 125, 30, "Toggle Wireframe");
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(505, 250, 95, 85, "Views");
      { new Fl_Button(525, 290, 60, 30, "Top");
      } // Fl_Button* o
      { new Fl_Button(525, 255, 60, 30, "Side");
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(510, 422, 260, 28, "Vertex Height");
      { Fl_Slider* o = new Fl_Slider(520, 426, 230, 24);
        o->type(1);
      } // Fl_Slider* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(625, 331, 125, 64, "No. of Subdivisions");
      { Fl_Value_Input* o = new Fl_Value_Input(670, 336, 35, 28);
        o->labeltype(FL_NO_LABEL);
      } // Fl_Value_Input* o
      { new Fl_Button(649, 370, 80, 25, "Fractalize!");
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Window* o
}
