// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef MiniMaya_h
#define MiniMaya_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_TREE.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Value_Input.H>

class TreeView {
public:
  TreeView();
};
#endif
